package view;

import controller.MainController;
import javax.swing.JOptionPane;

/**
 *
 * @author Yannick Lagger lagger.yannick@gmail.com
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form test
     */
    public MainView(MainController mainc) {
        this.mainc = mainc;
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titel = new javax.swing.JLabel();
        path = new javax.swing.JTextField();
        brows = new javax.swing.JButton();
        prefix = new javax.swing.JTextField();
        date = new javax.swing.JLabel();
        sufix = new javax.swing.JTextField();
        nameExampleLabel = new javax.swing.JLabel();
        nameExampleValue = new javax.swing.JLabel();
        rename = new javax.swing.JButton();
        shiftLabel = new javax.swing.JLabel();
        year = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        month = new javax.swing.JTextField();
        day = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        hours = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        minutes = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        defaultValue = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titel.setText("Photo rename");
        titel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        brows.setText("Brows");
        brows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browsActionPerformed(evt);
            }
        });

        prefix.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                prefixKeyReleased(evt);
            }
        });

        date.setText("- date -");

        sufix.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sufixKeyReleased(evt);
            }
        });

        nameExampleLabel.setText("Name example :");

        nameExampleValue.setText(mainc.formatCurrentDate());
        nameExampleValue.setToolTipText("");

        rename.setText("Rename");
        rename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renameActionPerformed(evt);
            }
        });

        shiftLabel.setText("Shift :");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Years");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Months");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Days");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Hours");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Minutes");

        file.setText("File");

        defaultValue.setText("New");
        defaultValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultValueActionPerformed(evt);
            }
        });
        file.add(defaultValue);

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        file.add(exit);

        menuBar.add(file);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(shiftLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(year))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(month))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(day, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hours, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(minutes, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(rename)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameExampleLabel)
                                .addGap(18, 18, 18)
                                .addComponent(nameExampleValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(prefix, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sufix))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(brows)))))
                .addContainerGap(40, Short.MAX_VALUE))
            .addComponent(titel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titel)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brows))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prefix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date)
                    .addComponent(sufix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameExampleLabel)
                    .addComponent(nameExampleValue))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shiftLabel)
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minutes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rename)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void browsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browsActionPerformed
        fileChooser.setSelectedFile(new java.io.File(""));
        fileChooser.setDialogTitle("select folder");
        fileChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        int result = fileChooser.showOpenDialog(null);
        //On ouvre le fichier que si la personne a choisi [OK] et non [Cancel] ou fermé la fenêtre [X]
        if (result == 0) {
            this.path.setText(fileChooser.getSelectedFile().getAbsolutePath());
            mainc.getConfig().setPath(fileChooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_browsActionPerformed

    private void defaultValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultValueActionPerformed
        this.mainc.setDefaultValue();
        this.path.setText(null);
        this.prefix.setText(null);
        this.sufix.setText(null);
        this.year.setText(null);
        this.month.setText(null);
        this.day.setText(null);
        this.nameExampleValue.setText(this.mainc.getConfig().getName(mainc.formatCurrentDate()));
    }//GEN-LAST:event_defaultValueActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void prefixKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prefixKeyReleased
        this.mainc.getConfig().setPrefix(this.prefix.getText());
        this.nameExampleValue.setText(this.mainc.getConfig().getName(mainc.formatCurrentDate()));
    }//GEN-LAST:event_prefixKeyReleased

    private void sufixKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sufixKeyReleased
        this.mainc.getConfig().setSufix(this.sufix.getText());
        this.nameExampleValue.setText(this.mainc.getConfig().getName(mainc.formatCurrentDate()));
    }//GEN-LAST:event_sufixKeyReleased

    private void renameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renameActionPerformed
        mainc.getConfig().setShiftYear(this.year.getText());
        mainc.getConfig().setShiftMonth(this.month.getText());
        mainc.getConfig().setShiftDay(this.day.getText());
        mainc.getConfig().setShiftHoures(this.hours.getText());
        mainc.getConfig().setShiftMinutes(this.minutes.getText());
        if (mainc.getConfig().getPath() == null) {
            JOptionPane.showMessageDialog(null, "Please select a folder!");
        } else if (mainc.shiftValidity(this.year.getText()) && mainc.shiftValidity(this.month.getText()) && mainc.shiftValidity(this.day.getText()) 
                && mainc.shiftValidity(this.hours.getText()) && mainc.shiftValidity(this.minutes.getText())) {
            if (mainc.rename()) {
                JOptionPane.showMessageDialog(null, "Renaming is complete!");
            } else {
                JOptionPane.showMessageDialog(null, "Some pictures could not been renamed!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Shift is not valid!");
        }

    }//GEN-LAST:event_renameActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brows;
    private javax.swing.JLabel date;
    private javax.swing.JTextField day;
    private javax.swing.JMenuItem defaultValue;
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenu file;
    private javax.swing.JTextField hours;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTextField minutes;
    private javax.swing.JTextField month;
    private javax.swing.JLabel nameExampleLabel;
    private javax.swing.JLabel nameExampleValue;
    private javax.swing.JTextField path;
    private javax.swing.JTextField prefix;
    private javax.swing.JButton rename;
    private javax.swing.JLabel shiftLabel;
    private javax.swing.JTextField sufix;
    private javax.swing.JLabel titel;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
    private MainController mainc;
    public final static javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser(".");
}
